blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<slug:the_slug>/', views.detail, name="detail"),
]

password_generator/urls.py
from django.contrib import admin
from django.urls import path, include
from generator import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('generatedpassword/', views.password, name='password'), 
    path('passwordpage/', views.about, name='passwordpage'),

    # path('createpassword/', views.createpassword, name='createpassword'), 
    path('prime/', views.prime, name='prime'),
    path('primepage/', views.primepage, name='primepage'),

    path('fibo/', views.fibo, name='fibo'),
    path('fibopage/', views.fibopage, name='fibopage'),

    path('romain/', views.romain, name='romain'),
    path('romainpage/', views.romainpage, name='romainpage'),

    path('factor/', views.factor, name='factor'),
    path('factorpage/', views.factorpage, name='factorpage'),

    path('base16/', views.base16, name='base16'),
    path('base16page/', views.base16page, name='base16page'),

    path('base2/', views.base2, name='base2'),
    path('base2page/', views.base2page, name='base2page'),

    path('seconddegre/', views.seconddegre, name='seconddegre'),
    path('seconddegrepage/', views.seconddegrepage, name='seconddegrepage'),

    path('cesaer/', views.cesaer, name='cesaer'),
    path('cesaerpage/', views.cesaerpage, name='cesaerpage'),

    path('sysdeq/', views.sysdeq, name='sysdeq'),
    path('sysdeqpage/', views.sysdeqpage, name='sysdeqpage'),

    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

generator/models.py
# from django.db import models
# from django.contrib.auth.models import User

# class PassWord2(models.Model):
# 	"""docstring for todoobject"""
# 	site = models.CharField(max_length = 100, null=True)
# 	password = models.TextField(blank = True, null=True)
# 	userps = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
# 	# store the relationship between a user and a object
# 	def __str__(self):
# 		return self.site

generator/forms.py
# from django.forms import ModelForm
# from .models import PassWord2

# class PassWordForm(ModelForm):
# 	class Meta:
# 		model = PassWord2
# 		fields = ['site', 'password']
# 			

generator/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from .forms import PassWordForm
# from .models import PassWord2
import random as stdlib_random
from scipy import *
from django.db import IntegrityError

import matplotlib.pyplot as plt


from matplotlib import pylab
from pylab import *
import PIL, PIL.Image
from io import BytesIO


# Create your views here.

def home(request):
	return render(request, 'generator/home.html')

def about(request):
	return render(request, 'generator/about.html')

def primepage(request):
	return render(request, 'generator/primepage.html')

def fibopage(request):
	return render(request, 'generator/fibopage.html')

def romainpage(request):
	return render(request, 'generator/romainpage.html')

def factorpage(request):
	return render(request, 'generator/factorpage.html')

def base16page(request):
	return render(request, 'generator/base16page.html')
	
def base2page(request):
	return render(request, 'generator/base2page.html')

def seconddegrepage(request):
	return render(request, 'generator/seconddegrepage.html')

def cesaerpage(request):
	return render(request, 'generator/cesaerpage.html')

def sysdeqpage(request):
	return render(request, 'generator/sysdeqpage.html')

def pgcd(a,b):
    """pgcd(a,b): calcul du 'Plus Grand Commun Diviseur' entre les 2 nombres entiers a et b"""
    while b!=0:
        r=a%b
        a,b=b,r
    return a


def sysdeq(request):
	a = int(request.GET.get('a'))
	b = int(request.GET.get('b'))
	c = int(request.GET.get('c'))
	ap = int(request.GET.get('ap'))
	bp = int(request.GET.get('bp'))
	cp = int(request.GET.get('cp'))
	try:
		d = int(request.GET.get('d'))
		dp = int(request.GET.get('dp'))
		app = int(request.GET.get('app'))
		bpp = int(request.GET.get('bpp'))
		cpp = int(request.GET.get('cpp'))
		dpp = int(request.GET.get('dpp'))
	except TypeError:
		d = 'a'
		dp = '0'
		app = '0'
		bpp = '0'
		cpp = '0'
		dpp = '0'


	if d == 'a':
		x = 0
		y = 0
		z = None
	  	# calculating the determinant of matrix 
		detx = b * cp - bp * c # np.linalg.det(dx)
		dety = a * cp - ap * c 
		detc = a * bp - ap * b
		print(dety)
		print(detx)
		print(detc)
		if detc == 0:
			if (a * bp == ap * b) and (a * cp != ap * c):
				x = "Les droites sont strictement paralleles"
				y = "Le systeme n'admet pas de solution"
				return render(request, 'generator/sysdeq.html', {'x':x, 'y':y})
			elif (a * bp == ap * b) and (a * cp == ap * c):
				x = "Les droites sont confondues"
				y = "Tous les couples (x;y) qui verifient l'equation ax+by+c=0 sont solutions, il y en a une infinite"
				return render(request, 'generator/sysdeq.html', {'x':x, 'y':y})
		else:
			x = detx/detc
			y = -(dety/detc)  
			return render(request, 'generator/sysdeq.html', {'x':x, 'y':y})
	else:
		x = 0
		y = 0
		z = 0

		detx = (b * ((cp * dpp) - (cpp * dp))) + (c * ((bpp * dp) - (bp * dpp))) + (d * ((bp * cpp) - (bpp * cp)))
		dety = (a * ((cp * dpp) - (cpp * dp))) + (c * ((app * dp) - (ap * dpp))) + (d * ((ap * cpp) - (app * cp)))
		detz = (a * ((bp * dpp) - (bpp * dp))) + (b * ((app * dp) - (ap * dpp))) + (d * ((ap * bpp) - (app * bp)))
		detd = (a * ((bp * cpp) - (bpp * cp))) + (b * ((app * cp) - (ap * cpp))) + (c * ((ap * bpp) - (app * bp)))
		print(detx)
		print(dety)
		print(detz)
		print(detd)
		if detd == 0:
			x = "si les coeficients (a,b,c,d) sont proportionnels alors les plans P1, P2 et P3 sont confondus"
			y = "si les coeficients (a,b,c) sont proportionnels alors les plans P1, P2 et P3 sont paralleles"
			z = "Les plans se coupent par une droite"
			return render(request, 'generator/sysdeq.html', {'x':x, 'y':y, 'z': z})			

		else:
			x = -detx/detd
			y = dety/detd
			z = -detz/detd
			return render(request, 'generator/sysdeq.html', {'x':x, 'y':y, 'z': z})

def cesaer(request):
	try:
		string = request.GET.get('text')
		decalage = int(request.GET.get('x'))
		x = 0
		l = ""
		for i in string:
		    if (ord(i) >= 65 and ord(i) <= (90 - decalage)) or (ord(i) >= 97 and ord(i) <= (122 - decalage)):
		        i = ord(i) + decalage
		        l = l + chr(i)
		        x += 1
		    elif (ord(i) >= (90 - decalage) and ord(i) <= 90) or (ord(i) >= (122 - decalage) and ord(i) <= 122):
		        i = ord(i) + decalage - 26
		        l = l + chr(i)
		        x += 1
		    else:
		        l = l + i
		print(l)
		return render(request, 'generator/cesaer.html', {'l': l})
	except:
		return render(request, 'generator/cesaerpage.html', {'error': "Vous avez entre des valeurs incorrectes"})

def seconddegre(request):
	try:
		a = int(request.GET.get('a'))
		b = int(request.GET.get('b'))
		c = int(request.GET.get('c'))
		delta = b**2 - 4 * a * c
		string_equation = f"Pour l'equation: {a}x2 + {b}x + {c} = 0 // Discriminant egale a {delta}"
		maxi = -b/(2*a)
		if delta < 0:
			string_title = "L'equation n'a pas de solution"
		elif delta == 0:
			string_title = f"L'equation n'admet qu'une solution x0 = {maxi:.2f}"
		elif delta > 0:
			x1 = (-b-sqrt(delta))/(2*a)
			x2 = (-b+sqrt(delta))/(2*a)
			string_title = f"L'equation admet deux solutions x1 = {x1:.2f} et x2 = {x2:.2f}"


		x = arange(maxi - 10, maxi + 10, 0.01)
		s = a*x**2 + b*x + c
		plot(x, s)

		xlabel(string_equation)
		ylabel('ylabel(Y)')

		title(string_title)
		grid(True)

		# Store image in a string buffer
		buffer = BytesIO() #.StringIO()
		canvas = pylab.get_current_fig_manager().canvas
		canvas.draw()
		pilImage = PIL.Image.frombytes("RGB", canvas.get_width_height(), canvas.tostring_rgb())
		pilImage.save(buffer, "PNG")
		pylab.close()

		# Send buffer in a http response the the browser with the mime type image/png set
		return HttpResponse(buffer.getvalue(), content_type="image/png")
	except:
		return render(request, 'generator/seconddegrepage.html', {'error':'Vous devez renter un nombre'})

def password(request):

	characters = list('abcdefghijklmnopqrstuvwxyz')

	if request.GET.get('uppercase'):
		characters.extend(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')) #pour ajouter les capital a la liste
	if request.GET.get('numbers'):
		characters.extend(list('0123456789')) #pour ajouter les capital a la liste
	if request.GET.get('special'):
		characters.extend(list('!@#$%^&*()-_=+')) #pour ajouter les capital a la liste
	try:
		length = int(request.GET.get('length')) # pour donner la valeur choisi dans le selector, on vient chercher le name dans le tag select de home.html
											# si on met pas int 'str' object cannot be interpreted as an integer
		thepassword = ''

		for x in range(length):
			thepassword += stdlib_random.choice(characters)

		return render(request, 'generator/password.html', {'password':thepassword})
	except:
		return render(request, 'generator/about.html', {'error':'Vous devez renter un nombre'})

def prime(request):
	try:
		num = int(request.GET.get('num'))
		
		
		counter_prime = 0
		prime = 0
		#rac = int(num ** 0.5) + 1
		listprime = []
		for i in range(2,num):
			counter_prime = 0
			for x in range(2,i):
				if i%x == 0:
					counter_prime += 1
				else:
					counter_prime = counter_prime
			if counter_prime == 0:
				listprime.append(i)
				prime += 1
		# print(listprime)
		#return prime
		return render(request, 'generator/prime.html', {'test':listprime})
	except ValueError:
			return render(request, 'generator/primepage.html', {'error':'Vous devez renter un nombre'})


def base16(request):
	choix = request.GET.get('choix')
	if choix == '1':

		try:
			M = int(request.GET.get('num'))
			dico = dict([('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'),('6', '6'), ('7', '7'), ('8', '8'),
		    ('9', '9'), ('10', 'A'), ('11', 'B'), ('12', 'C'), ('13', 'D'), ('14', 'E'),('15', 'F'), 
		    ])

			m = M
			base = 16
			x = 0
			if m <= base:
				x = 1
			else:
				while m >= base:
					m = M / (base ** x)
					if m > base:
						x += 1

			list16 = []
			for i in range(x,0,-1):
			    if i > 1:
			        d = M // base ** i
			        r = M % base ** i
			        list16.append(d)
			        M = r
			    else:
			        d = M // base ** i
			        r = M % base ** i
			        list16.append(d)
			        list16.append(r)
			       
			txt = ''
			for i in list16:
			    txt = txt + dico[str(i)]
			    
			txt = '0x' + txt
			return render(request, 'generator/base16.html', {'b16':txt})
		except ValueError:
				return render(request, 'generator/base16page.html', {'error':'Votre saisi contient un caractere non autorise'})
	else:
		dico = dict([('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5),('6', 6), ('7', 7), ('8', 8),
		    ('9', 9), ('A', 10), ('B', 11), ('C', 12), ('D', 13), ('E', 14),('F', 15), ('a', 10), ('b', 11), 
		    ('c', 12), ('d', 13), ('e', 14),('f', 15),
		    ])

		M = request.GET.get('num')
		base = 16
		m = M
		x = []
		y = 0
		increment = 0

		for i in M:
		    if i in dico.keys():
		        i = dico[i]
		        x.append(i)
		    else:
		        return render(request, 'generator/base16page.html', {'error':'Votre saisi contient un caractere non autorise'})

		for i in x[::-1]:
		    y = y + i * base ** increment
		    increment += 1
		return render(request, 'generator/base16.html', {'b16':y})


def base2(request):
	choix = request.GET.get('choix')
	if choix == '1':

		try:
			M = int(request.GET.get('num'))
			dico = dict([('0', '0'), ('1', '1')])

			m = M
			base = 2
			x = 0
			if m <= base * 4:
				x = 3
			else:
				while m >= base:
					m = M / (base ** x)
					if m > base:
						x += 1

			print(x)
			list16 = []
			for i in range(x,0,-1):
			    if i > 1:
			        d = M // base ** i
			        r = M % base ** i
			        list16.append(d)
			        M = r
			    else:
			        d = M // base ** i
			        r = M % base ** i
			        list16.append(d)
			        list16.append(r)
			       
			txt = ''
			for i in list16:
			    txt = txt + dico[str(i)]
			    
			txt = '0b' + txt
			return render(request, 'generator/base2.html', {'b16':txt})
		except ValueError:

generator/templates/generator/about.html
{% extends 'generator/base.html' %}
{% block content %}
<div class="container text-center mt-4">
	<h1 class="py-3">Generateur de mot de passe</h1>

	<div class="row">
		<div class="col">
<h2>{{ error }}</h2>
		<form action="{% url 'password' %}" class="py-5">
  <div class="form-group ">

    
    <input type="text" name="length" class="form-control col-5 mx-auto" placeholder="Taille du mot de passe">

</div>
  <div class="form-group form-check">
    <input width="20" type="checkbox" name="numbers" class="form-check-input">
    <label class="form-check-label" for="exampleCheck1">Ajouter des nombres</label>
  </div>
      <div class="form-group form-check">
    <input type="checkbox" name="special" class="form-check-input">
    <label class="form-check-label" for="exampleCheck1">Ajouter des caracteres speciaux</label>
  </div>
    <div class="form-group form-check">
    <input type="checkbox" name="uppercase" class="form-check-input">
    <label class="form-check-label" for="exampleCheck1">Ajouter des lettres en capitales</label>
  </div>
  <input type="submit" name="Generate Password" class="btn btn-primary btn-lg mt-4">
</form>


		</div>
	</div>
</div>

{% endblock %}

generator/templates/generator/base.html
<!DOCTYPE html>
<html>
<head>
	    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
	<title></title>
</head>
<body>


<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container">
    <a class="navbar-brand linknav" href="{% url 'home' %}">
        
        <span>Un peu de sciences</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link linknavbar" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link linknavbar" href="https://www.linkedin.com/in/merry-de-lassus-saint-genies-438601104/" target="_blank">Linkedin</a>
                </li>  
                <li class="nav-item">
                    <a class="nav-link linknavbar" href="https://www.instagram.com/merrypoppinns/?hl=fr" target="_blank">Instagram</a>
                </li>
                <li>
                    <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
                </li>  
        </ul>
    </div>
</div>
</nav>
<div class='col-10 col-md-6 mx-auto bg-light'>
{% block content %}{% endblock %}
</div>
</body>
</html>

generator/templates/generator/base16.html
{% extends 'generator/base.html' %}
{% block content %}

<div class="container text-center mt-4">
<h1 class="py-3">Votre nombre en base 16</h1>
	<div class="row">
		<div class="col">

		<h2 class="alert alert-success">{{ b16 }}</h2> 
		<!-- {{ password }} renvoie a la fonction dans views -->
		<br>
			<div class="row">
				<div class="col">
					<a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
				</div>
				<div class="col">
					<a href="{% url 'base16page' %}" class="btn btn-primary">Un nouveau?</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

generator/templates/generator/base2.html
{% extends 'generator/base.html' %}
{% block content %}
<div class="container text-center mt-4">
<h1 class="py-3">Votre nombre en base 2</h1>
	<div class="row">
		<div class="col">

		<h2 class="alert alert-success">{{ b16 }}</h2> 
		<!-- {{ password }} renvoie a la fonction dans views -->
		<br>
			<div class="row">
				<div class="col">
					<a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
				</div>
				<div class="col">
					<a href="{% url 'base2page' %}" class="btn btn-primary">Un nouveau?</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<div class="container text-center">
<h1>Your base 2 is :</h1>
<h2 class="alert alert-success">{{ b16 }}</h2> 
<!-- {{ password }} renvoie a la fonction dans views -->
<br>
<a href="{% url 'home' %}" class="btn btn-danger">home</a>
<br>
<a href="{% url 'base2page' %}" class="btn btn-danger">Again</a>
</div>

generator/templates/generator/cesaer.html
{% extends 'generator/base.html' %}
{% block content %}

<div class="container text-center mt-4">
	<h1 class="py-3">Message encode</h1>
	<div class="row">
		<div class="col">
			
			<h2 class="alert alert-success">{{ l }}</h2> 
			<!-- {{ password }} renvoie a la fonction dans views -->
			<br>
			  <div class="row">
    <div class="col">
      <a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
    </div>
    <div class="col">
      <a href="{% url 'cesaerpage' %}" class="btn btn-primary">Un nouveau?</a>
    </div>
  </div>
		</div>
	</div>
</div>

{% endblock %}

generator/templates/generator/factor.html
{% extends 'generator/base.html' %}
{% block content %}

<div class="container text-center mt-4">
	<h1 class="py-3">Voici la decomposition en facteur premier</h1>
	<div class="row">
		<div class="col">
			
			<h2 class="alert alert-success">{{ phrase }}</h2> 
			<!-- {{ password }} renvoie a la fonction dans views -->
			<br>
			  <div class="row">
    <div class="col">
      <a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
    </div>
    <div class="col">
      <a href="{% url 'factorpage' %}" class="btn btn-primary">Un nouveau?</a>
    </div>
  </div>
		</div>
	</div>
</div>

{% endblock %}

generator/templates/generator/fibo.html
{% extends 'generator/base.html' %}
{% block content %}

<div class="container text-center mt-4">
	<h1 class="py-3">Voici les iterations de la suite de Fibonacci</h1>
	<div class="row">
		<div class="col">
			
			<h2 class="alert alert-success">{{ fibz }}</h2> 
			<!-- {{ password }} renvoie a la fonction dans views -->
			<br>
			  <div class="row">
    <div class="col">
      <a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
    </div>
    <div class="col">
      <a href="{% url 'fibopage' %}" class="btn btn-primary">Une Autre?</a>
    </div>
  </div>
		</div>
	</div>
</div>

{% endblock %}

generator/templates/generator/fibopage.html
{% extends 'generator/base.html' %}
{% block content %}

<div class="container text-center mt-4">
	<h1 class="py-3">Choisissez une iteration</h1>

	<div class="row">
		<div class="col">
<h2> {{ error }} </h2>
		<form action="{% url 'fibo' %}" class="py-5">
  <div class="form-group ">

    <input type="text" name="num" class="form-control col-5 mx-auto" placeholder="Votre iteration">
<div class="row">

    <div class="col">
     <input type="submit" class="btn btn-primary btn-lg mt-4">
    </div>
</div>
{% endblock %}

generator/templates/generator/password.html
{% extends 'generator/base.html' %}
{% block content %}

<div class="container text-center mt-4">
<h1 class="py-3">Votre mot de passe</h1>
	<div class="row">
		<div class="col">
<h2> {{ error }} </h2>
		<h2 class="alert alert-success">{{ password }}</h2> 
		<!-- {{ password }} renvoie a la fonction dans views -->
		<br>
			<div class="row">
				<div class="col">
					<a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
				</div>
				<div class="col">
					<a href="{% url 'passwordpage' %}" class="btn btn-primary">Un nouveau?</a>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

generator/templates/generator/prime.html
{% extends 'generator/base.html' %}
{% block content %}
<div class="container text-center mt-4">
	<h1 class="py-3">Liste de nombres premiers</h1>
	<div class="row">
		<div class="col">
			
			<h2 class="alert alert-success">{{ test }}</h2> 
			<!-- {{ password }} renvoie a la fonction dans views -->
			<br>
			  <div class="row">
    <div class="col">
      <a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
    </div>
    <div class="col">
      <a href="{% url 'primepage' %}" class="btn btn-primary">Un nouveau?</a>
    </div>
  </div>
		</div>
	</div>
</div>
{% endblock %}

generator/templates/generator/romain.html
{% extends 'generator/base.html' %}
{% block content %}

<div class="container text-center mt-4">
	<h1 class="py-3">Voici votre nombre en chiffre romain</h1>
	<div class="row">
		<div class="col">
			
			<h2 class="alert alert-success">{{ ro }}</h2> 
			<!-- {{ password }} renvoie a la fonction dans views -->
			<br>
			  <div class="row">
    <div class="col">
      <a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
    </div>
    <div class="col">
      <a href="{% url 'romainpage' %}" class="btn btn-primary">Un nouveau?</a>
    </div>
  </div>
		</div>
	</div>
</div>

{% endblock %}

generator/templates/generator/seconddegrepage.html
{% extends 'generator/base.html' %}
{% block content %}

<div class=" container text-center mt-4">
	<h1 class="py-2">Equation du second degre</h1>
	<h2>{{ error }}</h2>
<form target="_blank" action="{% url 'seconddegre' %}" class="py-3">
	
<br>
	<input size="2" type="text" name="a">x^2 + <input size="2" type="text" name="b">bx + <input size="2" type="text" name="c">= 0
<br>
	<input type="submit" class="btn btn-primary btn-lg my-3">
<br>
<a href="{% url 'home' %}" class="btn btn-danger">home</a>

</form>
</div>
{% endblock %}

generator/templates/generator/sysdeq.html
{% extends 'generator/base.html' %}
{% block content %}

<div class="container text-center mt-4">
	<h1 class="py-3">Voici la resolution de votre systeme d'equations</h1>
	<div class="row">
		<div class="col">
			
			<h2 class="alert alert-success">x = {{ x }}</h2> 
			<h2 class="alert alert-success">y = {{ y }}</h2>
			{% if z %}
			<h2 class="alert alert-success">z = {{ z }}</h2>
			{% endif %}
			<!-- {{ password }} renvoie a la fonction dans views -->
			<br>
			  <div class="row">
    <div class="col">
      <a href="{% url 'home' %}" class="btn btn-danger mb-3">Retour a l'accueil</a>
    </div>
    <div class="col">
      <a href="{% url 'sysdeqpage' %}" class="btn btn-primary">Une Autre?</a>
    </div>
  </div>
		</div>
	</div>
</div>

{% endblock %}

generator/templates/generator/sysdeqpage.html
{% extends 'generator/base.html' %}
{% block content %}

<div class=" container text-center mt-4">
	<h1 class="py-2">Equation du premier degre</h1>
	<h2>{{ error }}</h2>
<div class="form-check">
  <input class="selec form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
  <label class="form-check-label" for="exampleRadios1">
    2
  </label>
</div>

<div class="form-check">
  <input class="selec form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
  <label class="form-check-label" for="exampleRadios2">
    3
  </label>
</div>
<form action="{% url 'sysdeq' %}" class="degre2 py-3" id="degre2">
<br>
	<input size="2" type="text" name="a">x + <input size="2" type="text" name="b">y + <input size="2" type="text" name="c"> = 0
<br>
<input size="2" type="text" name="ap">x + <input size="2" type="text" name="bp">y + <input size="2" type="text" name="cp"> = 0
<br>
	<input type="submit" class="btn btn-primary btn-lg my-3">
<br>
<a href="{% url 'home' %}" class="btn btn-danger">home</a>

</form>

<form action="{% url 'sysdeq' %}" class="degre3 py-3" id="degre3">
<br>
	<input size="2" type="text" name="a">x + <input size="2" type="text" name="b">y + <input size="2" type="text" name="c">z +<input size="2" type="text" name="d"> = 0
<br>
<input size="2" type="text" name="ap">x + <input size="2" type="text" name="bp">y + <input size="2" type="text" name="cp">z +<input size="2" type="text" name="dp"> = 0
<br>
<input size="2" type="text" name="app">x + <input size="2" type="text" name="bpp">y + <input size="2" type="text" name="cpp">z +<input size="2" type="text" name="dpp"> = 0
<br>
	<input type="submit" class="btn btn-primary btn-lg my-3">
<br>
<a href="{% url 'home' %}" class="btn btn-danger">home</a>

</form>
</div>
<script type="text/javascript">

	var radios = document.getElementsByName("exampleRadios");
	var cardpayment =  document.getElementById("degre2");
	var internetpayment =  document.getElementById("degre3");
	internetpayment.style.display = 'none';
	/* If Credit Card is selected by default, add these two lines of code.
	cardpayment.style.display = 'block';   // show
	internetpayment.style.display = 'none';// hide
	*/

	for(var i = 0; i < radios.length; i++) {
	   radios[i].onclick = function() {
	     var val = this.value;
	     if(val == 'option1'){  // Assuming your value for radio buttons is radio1, radio2 and radio3.
	        cardpayment.style.display = 'block';   // show
	        internetpayment.style.display = 'none';// hide
	     }
	     else if(val == 'option2'){
	         cardpayment.style.display = 'none';
	         internetpayment.style.display = 'block';
	     }    

	  }
	}
</script>

{% endblock %}

	var selec = $(".selec")
	if (selec == 1) {
		console.log(selec.value)
	} else {
		console.log(selec.value)
	}
		$(":radio[name=exampleRadios]").change(function() {
    console.log(this.value);
	});

	alert("Only one payment form is allowed")


		// var x = document.getElementsByName("exampleRadios").value;
	// var x2 = document.getElementById("exampleRadios2").value;
	// var y = $(".degre2")
	// var z = $(".degre3")
	// console.log(x)
	// if (x == 'option1'){
		// z.css('display', 'normal')
	// 	y.css('display', 'none')
	// }

	// else if (x2 == 'option2') {
	// 	// y.css('display', 'normal')
	// 	z.css('display', 'none')
	// }