blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<slug:the_slug>/', views.detail, name="detail"),
]

password_generator/urls.py
from django.contrib import admin
from django.urls import path, include
from generator import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('generatedpassword/', views.password, name='password'), 
    path('passwordpage/', views.about, name='passwordpage'),

    # path('createpassword/', views.createpassword, name='createpassword'), 
    path('prime/', views.prime, name='prime'),
    path('primepage/', views.primepage, name='primepage'),

    path('fibo/', views.fibo, name='fibo'),
    path('fibopage/', views.fibopage, name='fibopage'),

    path('romain/', views.romain, name='romain'),
    path('romainpage/', views.romainpage, name='romainpage'),

    path('factor/', views.factor, name='factor'),
    path('factorpage/', views.factorpage, name='factorpage'),

    path('base16/', views.base16, name='base16'),
    path('base16page/', views.base16page, name='base16page'),

    path('base2/', views.base2, name='base2'),
    path('base2page/', views.base2page, name='base2page'),

    path('seconddegre/', views.seconddegre, name='seconddegre'),
    path('seconddegrepage/', views.seconddegrepage, name='seconddegrepage'),

    path('cesaer/', views.cesaer, name='cesaer'),
    path('cesaerpage/', views.cesaerpage, name='cesaerpage'),

    path('sysdeq/', views.sysdeq, name='sysdeq'),
    path('sysdeqpage/', views.sysdeqpage, name='sysdeqpage'),

    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
	title = models.CharField(max_length = 100)
	description1 = models.CharField(max_length = 1000)
	description2 = models.CharField(max_length = 1000, blank = True, null = True)
	description3 = models.CharField(max_length = 1000, blank = True, null = True)
	description4 = models.CharField(max_length = 1000, blank = True, null = True)
	description5 = models.CharField(max_length = 1000, blank = True, null = True)
	description6 = models.CharField(max_length = 1000, blank = True, null = True)
	description7 = models.CharField(max_length = 1000, blank = True, null = True)
	description8 = models.CharField(max_length = 1000, blank = True, null = True)
	description9 = models.CharField(max_length = 1000, blank = True, null = True)
	description0 = models.CharField(max_length = 1000, blank = True, null = True)
	date = models.DateField()
	image1 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image2 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image3 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image4 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image5 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image6 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image7 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image8 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image9 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	image0 = models.ImageField(upload_to = 'blog/images/', blank = True, null = True)
	slug = models.SlugField(max_length=40)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
	blogs = Blog.objects.order_by('-date')
	return render(request, 'blog/all_blogs.html', {'blogs':blogs})

def detail(request, the_slug):
	blog = get_object_or_404(Blog, slug = the_slug)
	return render(request, 'blog/detail.html', {'blog':blog})

blog/templates/blog/all_blogs.html
{% extends 'generator/base.html' %}
{% block content %}
{% load i18n %}
<div class="container my-4">
	<h1 class="py-3 text-center">Il y a {{ blogs.count }} blog{{ blogs.count|pluralize }}</h1>
	<div class="row">
		<div class="col">
			{% for blog in blogs %}
				<a class="navblog" href="{% url 'blog:detail' blog.slug %}"><h2>{{ blog.title }}</h2>
			{% language 'fr' %}
				<h5>{{ blog.date|date:'l d F Y' }}</h5></a>
			{% endlanguage %}

				<p>{{ blog.description1|striptags|truncatechars:200 }}</p>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'generator/base.html' %}
{% block content %}

{% load i18n %}
<div class="container text-center my-4">
	<h1 class="py-3">{{ blog.title }}</h1>

	<div class="row">
		<div class="col">

			{% language 'fr' %}
				<h2>--{{ blog.date|date:'l d F Y' }}--</h2>
			{% endlanguage %}

			{% if blog.description1 %}
			<p class="my-3">{{ blog.description1|safe }}</p>
			{% endif %}
			{% if blog.image1 %}
			<img src="{{ blog.image1.url }}">
			{% endif %}

			{% if blog.description2 %}
			<p class="my-3">{{ blog.description2|safe }}</p>
			{% endif %}
			{% if blog.image2 %}
			<img src="{{ blog.image2.url }}">
			{% endif %}

			{% if blog.description3 %}
			<p class="my-3">{{ blog.description3|safe }}</p>
			{% endif %}
			{% if blog.image3 %}
			<img src="{{ blog.image3.url }}">
			{% endif %}

			{% if blog.description4 %}
			<p class="my-3">{{ blog.description4|safe }}</p>
			{% endif %}
			{% if blog.image4 %}
			<img src="{{ blog.image4.url }}">
			{% endif %}

			{% if blog.description5 %}
			<p class="my-3">{{ blog.description5|safe }}</p>
			{% endif %}
			{% if blog.image5 %}
			<img src="{{ blog.image5.url }}">
			{% endif %}

			{% if blog.description6 %}
			<p class="my-3">{{ blog.description6|safe }}</p>
			{% endif %}
			{% if blog.image6 %}
			<img src="{{ blog.image6.url }}">
			{% endif %}

			{% if blog.description7 %}
			<p class="my-3">{{ blog.description7|safe }}</p>
			{% endif %}
			{% if blog.image7 %}
			<img src="{{ blog.image7.url }}">
			{% endif %}

			{% if blog.description8 %}
			<p class="my-3">{{ blog.description8|safe }}</p>
			{% endif %}
			{% if blog.image8 %}
			<img src="{{ blog.image8.url }}">
			{% endif %}

			{% if blog.description9 %}
			<p class="my-3">{{ blog.description9|safe }}</p>
			{% endif %}
			{% if blog.image9 %}
			<img src="{{ blog.image9.url }}">
			{% endif %}

			{% if blog.description0 %}
			<p class="my-3">{{ blog.description0|safe }}</p>
			{% endif %}
			{% if blog.image0 %}
			<img src="{{ blog.image0.url }}">
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}